#!/usr/bin/env node
/**
 * Supabase + Vercel 환경 설정 자동화
 *
 * 필요한 Cursor Secrets (또는 환경 변수):
 *   SUPABASE_DB_PASSWORD      - Supabase 프로젝트 DB 비밀번호
 *   SUPABASE_SERVICE_ROLE_KEY - Supabase Settings > API > service_role
 *   VERCEL_TOKEN              - (선택) Vercel 환경 변수 자동 등록
 */

import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import crypto from 'crypto'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const PROJECT_REF = 'febqrvjexshypkjdvjgt'
const SUPABASE_URL = `https://${PROJECT_REF}.supabase.co`
const VERCEL_APP_URL = process.env.VERCEL_APP_URL || 'https://caringnote.vercel.app'

function getPassword() {
  return (
    process.env.SUPABASE_DB_PASSWORD ||
    process.env.DATABASE_PASSWORD ||
    process.env.POSTGRES_PASSWORD ||
    process.env.DB_PASSWORD ||
    ''
  )
}

function getServiceRoleKey() {
  return (
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.SUPABASE_SERVICE_KEY ||
    ''
  )
}

function buildConnectionStrings(password) {
  const encoded = encodeURIComponent(password)
  const ref = PROJECT_REF
  const host = `aws-1-ap-northeast-2.pooler.supabase.com`
  const direct = `postgresql://postgres.${ref}:${encoded}@${host}:5432/postgres`
  const pooled = `postgresql://postgres.${ref}:${encoded}@${host}:6543/postgres?pgbouncer=true`
  return { direct, pooled }
}

async function schemaExists(serviceKey) {
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/CareCenter?select=id&limit=1`, {
      headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` },
    })
    return res.ok
  } catch {
    return false
  }
}

function generateSecret() {
  return crypto.randomBytes(32).toString('base64')
}

async function createStorageBucket(serviceKey) {
  const res = await fetch(`${SUPABASE_URL}/storage/v1/bucket`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${serviceKey}`,
      'Content-Type': 'application/json',
      apikey: serviceKey,
    },
    body: JSON.stringify({ id: 'uploads', name: 'uploads', public: true }),
  })

  if (res.ok) {
    console.log('✅ Storage bucket "uploads" 생성 완료')
    return
  }

  const body = await res.json().catch(() => ({}))
  const msg = body.message || body.error || ''
  if (String(msg).includes('already exists')) {
    console.log('✅ Storage bucket "uploads" 이미 존재')
    return
  }

  console.warn('⚠️  Storage bucket 생성 실패:', msg || res.status)
}

async function pushVercelEnv(vars) {
  const token = process.env.VERCEL_TOKEN
  if (!token) {
    console.log('ℹ️  VERCEL_TOKEN 없음 — Vercel 환경 변수는 대시보드에서 수동 설정 필요')
    return
  }

  for (const [key, value] of Object.entries(vars)) {
    try {
      execSync(
        `printf '%s' "${value.replace(/"/g, '\\"')}" | npx vercel env add ${key} production preview development --force --token "${token}"`,
        { stdio: 'pipe', cwd: path.join(__dirname, '..') }
      )
      console.log(`✅ Vercel env: ${key}`)
    } catch {
      console.warn(`⚠️  Vercel env ${key} 설정 실패`)
    }
  }
}

async function main() {
  const password = getPassword()
  const serviceKey = getServiceRoleKey()

  if (!password) {
    console.error('❌ SUPABASE_DB_PASSWORD 환경 변수가 필요합니다.')
    console.error('   Supabase Dashboard > Settings > Database > Database password')
    process.exit(1)
  }

  if (!serviceKey) {
    console.error('❌ SUPABASE_SERVICE_ROLE_KEY 환경 변수가 필요합니다.')
    console.error('   Supabase Dashboard > Settings > API > service_role key')
    process.exit(1)
  }

  const { direct, pooled } = buildConnectionStrings(password)
  const nextAuthSecret = process.env.NEXTAUTH_SECRET || generateSecret()

  const envContent = `# Auto-generated by scripts/setup-env.mjs — DO NOT COMMIT
DATABASE_URL="${pooled}"
DIRECT_URL="${direct}"
NEXTAUTH_URL="${VERCEL_APP_URL}"
NEXTAUTH_SECRET="${nextAuthSecret}"
NEXT_PUBLIC_SUPABASE_URL="${SUPABASE_URL}"
SUPABASE_SERVICE_ROLE_KEY="${serviceKey}"
`

  const envPath = path.join(__dirname, '..', '.env.local')
  fs.writeFileSync(envPath, envContent)
  console.log('✅ .env.local 생성 완료')

  console.log('📦 DB 스키마 확인 중...')
  const exists = await schemaExists(serviceKey)
  if (exists) {
    console.log('✅ DB 스키마 이미 존재 (SQL Editor 또는 이전 push)')
  } else {
    execSync('npx prisma db push --accept-data-loss', {
      stdio: 'inherit',
      cwd: path.join(__dirname, '..'),
      env: { ...process.env, DATABASE_URL: pooled, DIRECT_URL: direct },
    })
    console.log('✅ DB 스키마 적용 완료')
  }

  // 시드 (Prisma → REST fallback)
  try {
    execSync('npx tsx prisma/seed.ts', {
      stdio: 'inherit',
      cwd: path.join(__dirname, '..'),
      env: { ...process.env, DATABASE_URL: direct, DIRECT_URL: direct },
    })
    console.log('✅ 시드 데이터 적용 완료 (Prisma)')
  } catch {
    console.log('ℹ️  Prisma 시드 실패 → REST API 시드 시도')
    execSync('node scripts/seed-rest.mjs', {
      stdio: 'inherit',
      cwd: path.join(__dirname, '..'),
      env: { ...process.env, NEXT_PUBLIC_SUPABASE_URL: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY: serviceKey },
    })
  }

  await createStorageBucket(serviceKey)

  const vercelVars = {
    DATABASE_URL: pooled,
    DIRECT_URL: direct,
    NEXTAUTH_URL: VERCEL_APP_URL,
    NEXTAUTH_SECRET: nextAuthSecret,
    NEXT_PUBLIC_SUPABASE_URL: SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: serviceKey,
  }

  await pushVercelEnv(vercelVars)

  console.log('\n🎉 설정 완료!')
  console.log(`   Supabase: ${SUPABASE_URL}`)
  console.log(`   Vercel:   ${VERCEL_APP_URL}`)

  if (!process.env.VERCEL_TOKEN) {
    console.log('\n📋 Vercel Dashboard → Settings → Environment Variables (Production/Preview/Development):')
    console.log('   DATABASE_URL, DIRECT_URL  ← Supabase Connect 모달에서 URI 복사')
    console.log(`   NEXTAUTH_URL=${VERCEL_APP_URL}`)
    console.log(`   NEXTAUTH_SECRET=${nextAuthSecret}`)
    console.log(`   NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}`)
    console.log('   SUPABASE_SERVICE_ROLE_KEY  ← Supabase Settings → API → service_role')
    console.log('\n   ⚠️  pooler 연결 실패 시: Reset database password (영문+숫자) → Restart project')
  }
}

main().catch((e) => {
  console.error('❌ 설정 실패:', e.message)
  process.exit(1)
})
